import type { InsertProperty, InsertMaintenance } from "@shared/schema";

export const SAMPLE_MAINTENANCE: Omit<InsertMaintenance, "propertyId">[] = [
  {
    title: "Kitchen sink leak repair",
    category: "Plumbing",
    status: "Completed",
    priority: "High",
    requestDate: "2026-05-12",
    dueDate: "2026-05-14",
    completedDate: "2026-05-15",
    cost: 285,
    vendor: "Cape Fear Plumbing",
    invoiceRef: "INV-1042",
    notes: "Replaced p-trap and supply line. 90-day warranty.",
  },
  {
    title: "HVAC annual service",
    category: "HVAC",
    status: "Completed",
    priority: "Medium",
    requestDate: "2026-04-02",
    dueDate: "2026-04-10",
    completedDate: "2026-04-08",
    cost: 165,
    vendor: "Carolina Comfort",
    invoiceRef: "INV-0987",
    notes: "Cleaned coils, replaced filter. Recommended replacing capacitor next season.",
  },
  {
    title: "Tenant reports flickering outlet",
    category: "Electrical",
    status: "In Progress",
    priority: "Urgent",
    requestDate: "2026-07-18",
    dueDate: "2026-07-21",
    completedDate: "",
    cost: 0,
    vendor: "Brightspark Electric",
    invoiceRef: "",
    notes: "Living room outlet. Electrician scheduled for Tuesday.",
  },
  {
    title: "Broken window latch — unit B",
    category: "Cosmetic",
    status: "Open",
    priority: "Low",
    requestDate: "2026-07-19",
    dueDate: "2026-07-28",
    completedDate: "",
    cost: 0,
    vendor: "",
    invoiceRef: "",
    notes: "Tenant requesting replacement latch on bedroom window.",
  },
  {
    title: "Quarterly pest treatment",
    category: "Pest Control",
    status: "Completed",
    priority: "Low",
    requestDate: "2026-06-01",
    dueDate: "2026-06-05",
    completedDate: "2026-06-03",
    cost: 95,
    vendor: "BugStop NC",
    invoiceRef: "INV-1101",
    notes: "Routine perimeter treatment, all 4 units.",
  },
];

export const SAMPLE_PROPERTIES: InsertProperty[] = [
  {
    name: "Maple Street Duplex",
    address: "412 Maple St",
    city: "Elizabethtown",
    state: "NC",
    zip: "28337",
    propertyType: "Duplex",
    purchaseDate: "2021-06-15",
    purchasePrice: 168000,
    currentValue: 215000,
    downPayment: 33600,
    loanAmount: 134400,
    loanBalance: 119500,
    interestRate: 4.25,
    mortgagePayment: 836,
    monthlyRent: 1850,
    otherIncome: 0,
    vacancyRate: 5,
    propertyTaxes: 165,
    insurance: 95,
    maintenance: 90,
    hoa: 0,
    propertyManagement: 148,
    utilities: 0,
    capexReserve: 93,
    otherExpenses: 0,
    notes: "Both units recently renovated. Long-term tenants in place.",
  },
  {
    name: "Oakwood Single Family",
    address: "78 Oakwood Dr",
    city: "Whiteville",
    state: "NC",
    zip: "28472",
    propertyType: "Single Family",
    purchaseDate: "2022-11-02",
    purchasePrice: 142000,
    currentValue: 165000,
    downPayment: 28400,
    loanAmount: 113600,
    loanBalance: 106200,
    interestRate: 5.75,
    mortgagePayment: 664,
    monthlyRent: 1450,
    otherIncome: 25,
    vacancyRate: 7,
    propertyTaxes: 120,
    insurance: 88,
    maintenance: 75,
    hoa: 0,
    propertyManagement: 116,
    utilities: 0,
    capexReserve: 73,
    otherExpenses: 0,
    notes: "Section 8 tenant. Rent guaranteed by housing authority.",
  },
  {
    name: "Riverbend Fourplex",
    address: "1205 Riverbend Ave",
    city: "Lumberton",
    state: "NC",
    zip: "28358",
    propertyType: "Fourplex",
    purchaseDate: "2023-03-20",
    purchasePrice: 295000,
    currentValue: 320000,
    downPayment: 73750,
    loanAmount: 221250,
    loanBalance: 214000,
    interestRate: 6.5,
    mortgagePayment: 1395,
    monthlyRent: 3400,
    otherIncome: 0,
    vacancyRate: 8,
    propertyTaxes: 245,
    insurance: 175,
    maintenance: 170,
    hoa: 0,
    propertyManagement: 272,
    utilities: 60,
    capexReserve: 170,
    otherExpenses: 40,
    notes: "4 units, 3 occupied. Unit 4 being turned for new tenant.",
  },
];
